services:
  mysql:
    container_name: "mysql"
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: gridge
      TZ: "Asia/Seoul"
    restart: always